beum_solum_demo_index:
    pattern:  /index
    defaults: { _controller: 'BeumSolumBundle:Demo:index' }

beum_solum_demo_paginated_table:
    pattern:  /paginated-table/{type}
    defaults: { _controller: 'BeumSolumBundle:Demo:paginatedTable', type: flat }

beum_solum_demo_ajax_data:
    pattern:  /ajax-data/{type}
    defaults: { _controller: 'BeumSolumBundle:Demo:ajaxData', type: flat }