beum_solum_bundle_demo:
  resource: "@BeumSolumBundle/Resources/config/routing/demo.yml"
  prefix:   /demo

beum_solum_bundle_test:
  resource: "@BeumSolumBundle/Resources/config/routing/test.yml"
  prefix:   /test