solum_test_jslint_select_file:
    pattern:  /jslint/
    defaults: { _controller: 'SolumBundle:Test:jsLintSelectFile' }

solum_test_jslint_review_file:
    pattern:  /jslint/review/
    defaults: { _controller: 'SolumBundle:Test:jsLintReviewFile' }

solum_test_jslint_files:
    pattern:  /jslint/files/
    defaults: { _controller: 'SolumBundle:Test:jsLintFiles' }

solum_test_jslint_run:
    pattern:  /jslint/run/
    defaults: { _controller: 'SolumBundle:Test:jsLintRun' }