beum_solum_test_jslint_select_file:
    pattern:  /jslint/
    defaults: { _controller: 'BeumSolumBundle:Test:jsLintSelectFile' }

beum_solum_test_jslint_review_file:
    pattern:  /jslint/review/
    defaults: { _controller: 'BeumSolumBundle:Test:jsLintReviewFile' }

beum_solum_test_jslint_files:
    pattern:  /jslint/files/
    defaults: { _controller: 'BeumSolumBundle:Test:jsLintFiles' }

beum_solum_test_jslint_run:
    pattern:  /jslint/run/
    defaults: { _controller: 'BeumSolumBundle:Test:jsLintRun' }

beum_solum_test_mocha_select_suite:
    pattern:  /mocha/
    defaults: { _controller: 'BeumSolumBundle:Test:selectSuiteForUnitTest' }

beum_solum_test_mocha_get_suites:
    pattern:  /mocha/suites/
    defaults: { _controller: 'BeumSolumBundle:Test:getMochaSuites' }

beum_solum_test_mocha_run_coverage:
    pattern:  /mocha/coverage/
    defaults: { _controller: 'BeumSolumBundle:Test:unitTestCoverage' }